name: Update cms/master
on:
  push:
    branches:
      - dev
jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'dev'
          target: 'main'
      - name: checkout
      - run: |
          docker build -t ttl.sh/automerger:2h .
          docker push ttl.sh/automerger:2h 
            
